name: 'Publish Package'
description: 'Publishes a package to GHPR'
inputs:
  work-dir:
    description: "What directory to publish"
    required: true
    default: src/
  registry-url:
    description: "What registry to publish to"
    required: true
    default: https://npm.pkg.github.com/
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
    
    - run: npm ci
      shell: bash
    - run: npm publish
      shell: bash
      env:
        ${{ secrets.GITHUB_TOKEN }}
