name: 'Publish Package'
description: 'Publishes a package to GHPR'
inputs:
  work-dir:
    required: true
  registry-url:
    required: true
runs:
  using: "composite"
  steps:
  - uses: actions/setup-node@v3
  
  - run: npm ci
    shell: bash
  - run: npm publish
    shell: bash
    env: 
      ${{ secrets.GITHUB_TOKEN }}
